// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller
import { application } from "./application"

import SelectInterfaceController from "./select_interface_controller.js"
application.register("select-interface", SelectInterfaceController)

import TitleUpdateController from "./title_update_controller.js"
application.register("title-update", TitleUpdateController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)
